#!/bin/bash

mkdir installers
wget http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-no-gl-v3.5.1_Linux_x86_64.sh -O ./installers/ArrayFire-no-gl-v3.5.1_Linux_x86_64.sh
chmod +x ./installers/ArrayFire-no-gl-v3.5.1_Linux_x86_64.sh

./installers/ArrayFire-no-gl-v3.5.1_Linux_x86_64.sh --prefix=/usr/local --skip-license

wget https://github.com/shapelets/khiva/releases/download/v0.1.0/khiva-v0.1.0-ci.sh -O ./installers/khiva-v0.1.0-ci.sh
chmod +x ./installers/khiva-v0.1.0-ci.sh

./installers/khiva-v0.1.0-ci.sh --prefix=/usr/local --skip-license

ldconfig

